---
abstract: 'Locally mirror a Google Drive folder structure'
author:
  - ':m) <matthias.bloch@puffin.ch>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-Drive-Simple-Mirror
version: 0.050
